spring:
  application:
    name: fooddelivery
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update